# Generated by Django 4.1.4 on 2023-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_user_location_id_user_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
